/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arizatakip;

import static arizatakip.yoneticiPaneli.arizalar;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author myusu
 */
public class musteriPaneli extends javax.swing.JFrame {
        static EntityManagerFactory emf =Persistence.createEntityManagerFactory("ArizaTakipPU");
        static EntityManager em=emf.createEntityManager();
        static Query q=em.createQuery("SELECT a FROM Arizalar a");
        static List <Arizalar> arizalar;
    DefaultTableModel dtm=new DefaultTableModel();
    public musteriPaneli() {
       Query q=em.createQuery("SELECT a FROM Arizalar a"); 
      arizalar=q.getResultList(); 
      
      initComponents();
        
        dtm.setColumnIdentifiers(new Object[]{"Arıza Id","Marka","Model","Arızası","Durumu"});
        tbl_tablo.setModel(dtm);
        dtm.setRowCount(0);
        
        
        for (int i = 0; i < arizalar.size(); i++) {
            if (arizalar.get(i).getMusteriId()==Giris.hangiKullanici) {
                String durum;
                if (arizalar.get(i).getDurumu()==0) {
                    durum="Beklemede";
                }else if (arizalar.get(i).getDurumu()==1) {
                    durum="Tamir ediliyor...";
                }else{
                    durum="Tamir edildi. Lütfen teslim alınız.";
                     Path p=Paths.get("c:","dosyalar",arizalar.get(i).getArizaId().toString()+".txt");
                    try {
                        FileReader fr = new FileReader(p.toFile());
                        String line;
                        BufferedReader br=new BufferedReader(fr);
                        while ((line=br.readLine())!=null){
                            txtDosya.setText(line);
                        }
                        br.close();
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(musteriPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(musteriPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                dtm.addRow(new Object[]{arizalar.get(i).getArizaId(), arizalar.get(i).getMarka(),arizalar.get(i).getModel(),arizalar.get(i).getAriza(),durum});
            }
                
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncikis = new javax.swing.JButton();
        txtmodel = new javax.swing.JTextField();
        txtmarka = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtariza = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnekle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_tablo = new javax.swing.JTable();
        btnSecileniAl = new javax.swing.JButton();
        txtDosya = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btncikis.setBackground(new java.awt.Color(255, 0, 0));
        btncikis.setText("OTURUMU KAPAT");
        btncikis.setBackground(Color.RED);
        btncikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncikisActionPerformed(evt);
            }
        });

        txtariza.setColumns(20);
        txtariza.setRows(5);
        jScrollPane1.setViewportView(txtariza);

        jLabel1.setText("ARAÇ MARKA");

        jLabel2.setText("ARAÇ MODEL");

        jLabel3.setText("ARIZASI");

        btnekle.setBackground(new java.awt.Color(51, 255, 51));
        btnekle.setText("ARIZA KAYIT");
        btnekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnekleActionPerformed(evt);
            }
        });

        tbl_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_tablo);

        btnSecileniAl.setText("SEÇİLEN ARACI TESLİM AL");
        btnSecileniAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecileniAlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtDosya, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncikis)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmarka, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnekle, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(btnSecileniAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncikis, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(txtDosya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmarka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnekle, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnSecileniAl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncikisActionPerformed
       Giris g=new Giris();
       g.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btncikisActionPerformed

    private void btnekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnekleActionPerformed
       try {
        Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app","app");
        String sqlInsert ="INSERT INTO ARIZALAR"
                + "(MUSTERI_ID,ARIZA,MARKA,MODEL,ARIZA_ID,DURUMU)"
                + "VALUES(?,?,?,?,?,?)";
        PreparedStatement psInsert=con.prepareStatement(sqlInsert);
        psInsert.setInt(1, Giris.hangiKullanici);
        psInsert.setString(2,txtariza.getText() );
        Random r=new Random();
        psInsert.setString(3,txtmarka.getText());
        psInsert.setString(4, txtmodel.getText());
        psInsert.setInt(5, r.nextInt(999999));
        psInsert.setInt(6, 0);
        psInsert.executeUpdate();
         con.commit();
        con.close();
      
         Query q=em.createQuery("SELECT a FROM Arizalar a");
         List <Arizalar> arizalar=q.getResultList();
         
        JOptionPane.showMessageDialog(null, "ARIZA KAYDEDİLDİ", "Tebrikler", 1);
    } catch (SQLException ex) {
           System.out.println(ex.getMessage());
    }
       arizalar=q.getResultList();
       
        dtm.setRowCount(0);
           for (int i = 0; i < arizalar.size(); i++) {
            if (arizalar.get(i).getMusteriId()==Giris.hangiKullanici) {
                String durum;
                if (arizalar.get(i).getDurumu()==0) {
                    durum="Beklemede";
                }else if (arizalar.get(i).getDurumu()==1) {
                    durum="Tamir ediliyor...";
                }else{
                    durum="Tamir edildi. Lütfen teslim alınız.";
                }
                dtm.addRow(new Object[]{arizalar.get(i).getArizaId(), arizalar.get(i).getMarka(),arizalar.get(i).getModel(),arizalar.get(i).getAriza(),durum});
            }
                
            
        }
        
    }//GEN-LAST:event_btnekleActionPerformed

    private void btnSecileniAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecileniAlActionPerformed
       
            for (int j = 0; j < arizalar.size(); j++) {
                if (Integer.parseInt(tbl_tablo.getValueAt(tbl_tablo.getSelectedRow(), 0).toString())==arizalar.get(j).getArizaId()) {
                    try {
                        Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app","app");
                        String sqlInsert ="DELETE FROM ARIZALAR WHERE ARIZA_ID= (?) ";
                        PreparedStatement psDelete=con.prepareStatement(sqlInsert);
                        psDelete.setInt(1, arizalar.get(j).getArizaId());
                        psDelete.executeUpdate();
                         con.commit();
                         con.close();
                         Path p =Paths.get("c:","dosyalar",arizalar.get(j).getArizaId().toString()+".txt");
                         Files.delete(p);
                        arizalar.remove(j);
                        dtm.removeRow(tbl_tablo.getSelectedRow());
                    } catch (SQLException ex) {
                        Logger.getLogger(musteriPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(musteriPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                    
                }   
            }
        
        
    }//GEN-LAST:event_btnSecileniAlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteriPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteriPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteriPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteriPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteriPaneli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSecileniAl;
    private javax.swing.JButton btncikis;
    private javax.swing.JButton btnekle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_tablo;
    private javax.swing.JLabel txtDosya;
    private javax.swing.JTextArea txtariza;
    private javax.swing.JTextField txtmarka;
    private javax.swing.JTextField txtmodel;
    // End of variables declaration//GEN-END:variables
}
