/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arizatakip;

import static arizatakip.musteriPaneli.arizalar;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author myusu
 */
public class yoneticiPaneli extends javax.swing.JFrame {

    DefaultTableModel dtm=new DefaultTableModel();
    DefaultTableModel dtm1=new DefaultTableModel();
     static EntityManagerFactory emf =Persistence.createEntityManagerFactory("ArizaTakipPU");
        static EntityManager em=emf.createEntityManager();
        static Query q=em.createQuery("SELECT a FROM Arizalar a");
        static List <Arizalar> arizalar;
    public yoneticiPaneli() {
        initComponents();
        arizalar=q.getResultList();
       
        dtm.setColumnIdentifiers(new Object[]{"Arıza ID", "Bilgi"});
        dtm1.setColumnIdentifiers(new Object[]{"Arıza Id", "Araç  Sahibi", "Araç Markası", "Araç Modeli", "Arızası"});
        dtm.setRowCount(0);
       
            for (int j = 0; j < arizalar.size(); j++) {
                if (arizalar.get(j).getDurumu()==0) {
                    dtm.addRow(new Object[]{arizalar.get(j).getArizaId(), arizalar.get(j).getMarka()+" : "+ arizalar.get(j).getModel()});
                    
                }
            }
        
        for (int i = 0; i < Giris.kullanicilar.size(); i++) {
            for (int j = 0; j < arizalar.size(); j++) {
                if (arizalar.get(j).getDurumu()==1&&Giris.kullanicilar.get(i).getKullaniciId()==arizalar.get(j).getMusteriId()) {
                    dtm1.addRow(new Object[]{arizalar.get(j).getArizaId(), Giris.kullanicilar.get(i).getAdi(),arizalar.get(j).getMarka(),arizalar.get(j).getModel(),arizalar.get(j).getAriza()});
                }
                
            }
        }
     tbleldekiler.setModel(dtm1);
     tblarizalar.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbleldekiler = new javax.swing.JTable();
        btncikis = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblarizalar = new javax.swing.JTable();
        btniceri = new javax.swing.JButton();
        btnbitis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbleldekiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbleldekiler);

        btncikis.setBackground(new java.awt.Color(255, 0, 0));
        btncikis.setText("OTURUMU KAPAT");
        btncikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncikisActionPerformed(evt);
            }
        });

        tblarizalar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblarizalar);

        btniceri.setText("İÇERİYE AL >>>");
        btniceri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniceriActionPerformed(evt);
            }
        });

        btnbitis.setText("TAMİR EDİLDİ");
        btnbitis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbitisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncikis, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btniceri, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnbitis, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncikis, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btniceri, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnbitis, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btniceriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniceriActionPerformed
        for (int i = 0; i < arizalar.size(); i++) {
            
                if (Integer.parseInt(dtm.getValueAt(tblarizalar.getSelectedRow(), 0).toString())==arizalar.get(i).getArizaId()) {
                    try {
                       
                        Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app","app");
                        String sqlInsert ="UPDATE ARIZALAR SET DURUMU=(?) WHERE ARIZA_ID=(?) ";
                        PreparedStatement psUpdate=con.prepareStatement(sqlInsert);
                        psUpdate.setInt(1, 1);
                         psUpdate.setInt(2, arizalar.get(i).getArizaId());
                        psUpdate.executeUpdate();
                         con.commit();
        con.close();
        arizalar.get(i).setDurumu(1);
            for (int j = 0; j < Giris.kullanicilar.size(); j++) {
                if (arizalar.get(i).getDurumu()==1&&Giris.kullanicilar.get(j).getKullaniciId()==arizalar.get(i).getMusteriId()) {
                    dtm1.addRow(new Object[]{arizalar.get(i).getArizaId(), Giris.kullanicilar.get(j).getAdi(),arizalar.get(i).getMarka(),arizalar.get(i).getModel(),arizalar.get(i).getAriza()});
                }
                
            }
             arizalar.remove(i);
            dtm.removeRow(tblarizalar.getSelectedRow());
            yoneticiPaneli y=new yoneticiPaneli();
            this.setVisible(false);
            y.setVisible(true);
                       
                    } catch (SQLException ex) {
                        Logger.getLogger(yoneticiPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            
        }
        
        
    }//GEN-LAST:event_btniceriActionPerformed

    private void btncikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncikisActionPerformed
       Giris g=new Giris();
       g.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btncikisActionPerformed

    private void btnbitisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbitisActionPerformed
        for (int i = 0; i < arizalar.size(); i++) {
           
                if (Integer.parseInt(dtm1.getValueAt(tbleldekiler.getSelectedRow(), 0).toString())==arizalar.get(i).getArizaId()) {
                    
                    try {
                        
                        Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app","app");
                        String sqlInsert ="UPDATE ARIZALAR SET DURUMU=(?) WHERE ARIZA_ID=(?) ";
                        PreparedStatement psUpdate=con.prepareStatement(sqlInsert);
                        psUpdate.setInt(1, 2);
                        psUpdate.setInt(2, arizalar.get(i).getArizaId());
                        psUpdate.executeUpdate();
                          con.commit();
                          con.close();
                        Path p=Paths.get("c:","dosyalar",arizalar.get(i).getArizaId().toString()+".txt");
                        Files.createFile(p);
                        BufferedWriter bw=new BufferedWriter(new FileWriter(p.toFile().toString()));
                        bw.write(arizalar.get(i).getArizaId()+" nolu arızanız tamamlanmıştır lütfen teslim alınız.");
                        bw.close();
                        
                        
                        dtm1.removeRow(tbleldekiler.getSelectedRow());
                        arizalar.remove(i);
                    } catch (SQLException ex) {
                        Logger.getLogger(yoneticiPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(yoneticiPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
        }
        
    }//GEN-LAST:event_btnbitisActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yoneticiPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yoneticiPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yoneticiPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yoneticiPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yoneticiPaneli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbitis;
    private javax.swing.JButton btncikis;
    private javax.swing.JButton btniceri;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblarizalar;
    private javax.swing.JTable tbleldekiler;
    // End of variables declaration//GEN-END:variables
}
